export const DEFAULT_ATTRIBUTES = [
	'class',
	'id',
	'style',
	'translate',
	'contenteditable',
	'hidden',
	'draggable',
	'spellcheck',
	'onclick',
	'on',
]

export const ALLOWED_ATTRIBUTES = {
	div: [...DEFAULT_ATTRIBUTES],
	h1: [...DEFAULT_ATTRIBUTES],
	h2: [...DEFAULT_ATTRIBUTES],
	h3: [...DEFAULT_ATTRIBUTES],
	h4: [...DEFAULT_ATTRIBUTES],
	h5: [...DEFAULT_ATTRIBUTES],
	h6: [...DEFAULT_ATTRIBUTES],
	p: [...DEFAULT_ATTRIBUTES],
	span: [...DEFAULT_ATTRIBUTES],
	table: [...DEFAULT_ATTRIBUTES],
	tbody: [...DEFAULT_ATTRIBUTES],
	td: [...DEFAULT_ATTRIBUTES],
	tr: [...DEFAULT_ATTRIBUTES],

	input: [
		...DEFAULT_ATTRIBUTES,
		'accept',
		'alt',
		'autofocus',
		'autocomplete',
		'height',
		'width',
		'max',
		'maxlength',
		'min',
		'pattern',
		'readonly',
		'src',
		'type',
		'value',
		'placeholder',
		'checked',
		'disabled',
		'required',
		'name',
		'step',
		'onmousemove',
	],

	textarea: [
		...DEFAULT_ATTRIBUTES,
		'autofocus',
		'cols',
		'rows',
		'maxlength',
		'placeholder',
		'readonly',
		'required',
		'value',
		'name',
		'wrap',
	],

	a: [
		...DEFAULT_ATTRIBUTES,
		'href',
		'download',
		'hreflang',
		'media',
		'ping',
		'referrerpolicy',
		'rel',
		'target',
		'type',
	],
	img: [
		...DEFAULT_ATTRIBUTES,
		'src',
		'alt',
		'height',
		'width',
		'crossorigin',
		'ismap',
		'loading',
		'longdesc',
		'referrerpolicy',
		'sizes',
		'srcset',
		'usemap',
	],

	button: [
		...DEFAULT_ATTRIBUTES,
		'autofocus',
		'disabled',
		'form',
		'formaction',
		'formenctype',
		'formmethod',
		'formnovalidate',
		'formtarget',
		'name',
		'type',
		'value',
	],

	form: [
		...DEFAULT_ATTRIBUTES,
		'accept-charset',
		'action',
		'action-xhr',
		'autocomplete',
		'enctype',
		'method',
		'name',
		'novalidate',
		'rel',
		'target',
	],
	label: [...DEFAULT_ATTRIBUTES, 'for', 'form'],

	select: [
		...DEFAULT_ATTRIBUTES,
		'autofocus',
		'disabled',
		'multiple',
		'name',
		'required',
		'size',
	],
	option: [...DEFAULT_ATTRIBUTES, 'disabled', 'label', 'selected', 'value'],

	fieldset: [...DEFAULT_ATTRIBUTES, 'disabled', 'form', 'name'],

	iframe: [
		...DEFAULT_ATTRIBUTES,
		'allow',
		'allowfullscreen',
		'allowpaymentrequest',
		'height',
		'loading',
		'name',
		'referrerpolicy',
		'sandbox',
		'src',
		'width',
	],

	video: [
		...DEFAULT_ATTRIBUTES,
		'autoplay',
		'controls',
		'height',
		'loop',
		'muted',
		'poster',
		'preload',
		'src',
		'width',
	],

	th: [...DEFAULT_ATTRIBUTES, 'abbr', 'colspan', 'headers', 'rowspan', 'scope'],

	output: [...DEFAULT_ATTRIBUTES, 'for', 'form', 'name'],

	canvas: [...DEFAULT_ATTRIBUTES, 'height', 'width'],

	// !AMP
	'amp-img': ['src', 'alt', 'width', 'height', 'layout', 'fallback'],
}
